In [1]:
def my_function():
    "This print a string"
    print("Hello from a function")

In [2]:
my_function()

Hello from a function


In [3]:
def printme(nama): # parameter
    "This print a nama string into this function"
    print(nama)

In [4]:
printme("Reza") # argument

Reza


In [5]:
printme("nama saya adalah ....")

nama saya adalah ....


In [11]:
def printme(nama, alamat):
    "This print a nama string into this function"
    print(nama)
    print(alamat)
    return

In [12]:
printme("Reza", "Solo")

Reza
Solo


In [13]:
printme(alamat="Solo", nama="Reza")

Reza
Solo


In [14]:
def printme(nama = "Reza", alamat = "Solo"):
    "This print a nama string into this function"
    print(nama)
    print(alamat)
    return

In [15]:
printme()

Reza
Solo


In [17]:
printme("Hacktiv8")

Hacktiv8
Solo


In [18]:
printme(alamat="Jakarta")

Reza
Jakarta


In [20]:
printme("Hacktiv8", "Jakarta")

Hacktiv8
Jakarta


In [28]:
def printinfo(arg1, *vartuple):
    "This prints a variable passed arguments"
    print("Output is: ")
    print(arg1)
    for var in vartuple:
        print(var)
    return;

In [29]:
printinfo(30)

Output is: 
30


In [30]:
printinfo(1, 2, 3, 4, 5, 6, 7, 8, 9)

Output is: 
1
2
3
4
5
6
7
8
9


In [35]:
sum = lambda arg1, vartuple: arg1 + vartuple;

In [36]:
sum(10, 20)

30

In [37]:
print("value of total:", sum(20, 20))

value of total: 40


In [40]:
def sum(arg1, arg2):
    total = arg1 + arg2
    totall = total + 50
    return total, totall

In [41]:
sum(10, 20)

(30, 80)

In [49]:
kucing = 20

def jumlahHewan():
    kelinci = 30
    hewan = kucing + kelinci
    return hewan

def tambahHewan():
    anjing = 20
    tambahan = anjing + kucing
    return tambahan

In [50]:
jumlahHewan()

50

In [51]:
tambahHewan()

40

In [52]:
import sys

In [53]:
sys.path

['C:\\Users\\spn',
 'C:\\Users\\spn\\Anaconda3\\python37.zip',
 'C:\\Users\\spn\\Anaconda3\\DLLs',
 'C:\\Users\\spn\\Anaconda3\\lib',
 'C:\\Users\\spn\\Anaconda3',
 '',
 'C:\\Users\\spn\\Anaconda3\\lib\\site-packages',
 'C:\\Users\\spn\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\spn\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\spn\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\spn\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\spn\\.ipython']

In [102]:
sys.path.append(r'/Users/spn/Desktop/')

In [103]:
sys.path

['C:\\Users\\spn',
 'C:\\Users\\spn\\Anaconda3\\python37.zip',
 'C:\\Users\\spn\\Anaconda3\\DLLs',
 'C:\\Users\\spn\\Anaconda3\\lib',
 'C:\\Users\\spn\\Anaconda3',
 '',
 'C:\\Users\\spn\\Anaconda3\\lib\\site-packages',
 'C:\\Users\\spn\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\spn\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\spn\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\spn\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\spn\\.ipython',
 '/Users/spn/Desktop/H8package',
 'Users\\spn\\Desktop\\H8package',
 'Users/spn/Desktop/H8package',
 'Users/spn/Desktop/',
 'Users/spn/Desktop',
 'Users/spn/Desktop',
 'Users/spn/Desktop/',
 '/Users/spn/Desktop/',
 '/Users/spn/Desktop/']

In [104]:
import mod

In [106]:
mod.s

AttributeError: module 'mod' has no attribute 's'

In [99]:
sys.path.append(r'/Users/spn/Desktop/')

In [100]:
import H8package.mod

In [90]:
!pip --version

pip 20.0.2 from C:\Users\spn\Anaconda3\lib\site-packages\pip (python 3.7)



In [91]:
!pip install requests

In [92]:
import requests

In [107]:
## numpy

In [108]:
import numpy as np

In [109]:
## Creating Array

a = np.array({1, 2, 3})

In [111]:
a

array({1, 2, 3}, dtype=object)

In [112]:
b = {1, 2, 3}

In [113]:
b

{1, 2, 3}

In [117]:
c = np.zeros(99)

In [118]:
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0.]


In [119]:
d = np.ones(100)

In [120]:
print(d)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


In [123]:
np.arange(4)

array([0, 1, 2, 3])

In [125]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
np.arange(0, 20, 2) # start, stop, step

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [131]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [132]:
print(arr)

[1 2 3 4 5 6 7 8]


In [135]:
np.append(arr, [1, 2]) # add

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [139]:
np.delete(arr, 2) # delete

array([1, 2, 4, 5, 6, 7, 8])

In [140]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [141]:
print(arr)

[2 1 5 3 7 4 6 8]


In [142]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [143]:
## Shape dan Size

In [156]:
array_example = np.array([
    [[0, 1, 2, 3],
     [4, 5, 6, 7]],
    [[0, 1, 2, 3],
     [4, 5, 6, 7]],
    [[0, 1, 2, 3],
     [4, 5, 6, 7]]
])

In [157]:
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [158]:
array_example.ndim

3

In [159]:
array_example.size

24

In [160]:
array_example.shape

(3, 2, 4)

In [161]:
# Reshape

In [162]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [163]:
b = a.reshape(3, 2)

In [164]:
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [165]:
a.reshape(6, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [166]:
# convert 1D to 2D

In [167]:
a

array([0, 1, 2, 3, 4, 5])

In [168]:
a.shape

(6,)

In [169]:
a2 = a[np.newaxis]
print(a2)
print(a2.shape)

[[0 1 2 3 4 5]]
(1, 6)


In [171]:
row_vector = a[np.newaxis, :]
print(row_vector)
print(row_vector.shape)

[[0 1 2 3 4 5]]
(1, 6)


In [174]:
col_vector = a[:, np.newaxis]
print(col_vector)
print(col_vector.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
(6, 1)


In [176]:
print(a.shape)

(6,)


In [179]:
d = np.expand_dims(a, axis=1)
print(d)
print(d.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
(6, 1)


In [180]:
e = np.expand_dims(a, axis=0)
print(e)
print(e.shape)

[[0 1 2 3 4 5]]
(1, 6)


In [181]:
## indexing and slicing

In [182]:
data = np.array([1, 2, 3])

In [183]:
data[0]

1

In [184]:
data[1]

2

In [186]:
data[0:2]

array([1, 2])

In [187]:
data[1:]

array([2, 3])

In [188]:
data[-2]

2

In [189]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [190]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [194]:
a[a<8]

array([1, 2, 3, 4, 5, 6, 7])

In [195]:
a[a>=8]

array([ 8,  9, 10, 11, 12])

In [202]:
lebih_lima = (a >= 5)

a[lebih_lima]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [203]:
a[(a > 2) & (a < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [204]:
# Create array from existing data

In [205]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [208]:
arr1 = arr[3:9]

In [209]:
print(arr1)

[4 5 6 7 8 9]


In [212]:
a_1 = np.array([[1, 1],
                [2, 2]])

print(a_1)

[[1 1]
 [2 2]]


In [213]:
a_2 = np.array([[3, 3],
                [4, 4]])

print(a_2)

[[3 3]
 [4 4]]


In [214]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [215]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [217]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [219]:
np.hsplit(arr, 5)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]

In [220]:
# view dan copy

In [221]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [222]:
b = a.view()

In [223]:
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [224]:
c = a.copy()

In [225]:
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [226]:
# basic array operations

In [227]:
a_1

array([[1, 1],
       [2, 2]])

In [230]:
a_2

array([[3, 3],
       [4, 4]])

In [231]:
a_2 = a_1

In [232]:
a_2 + a_1

array([[2, 2],
       [4, 4]])

In [228]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [229]:
arr.sum()

55

In [233]:
a_1

array([[1, 1],
       [2, 2]])

In [234]:
a_1.sum()

6

In [235]:
a_1.sum(axis=0)

array([3, 3])

In [236]:
a_1.sum(axis=1)

array([2, 4])

In [237]:
a_1 * 1.6

array([[1.6, 1.6],
       [3.2, 3.2]])

In [238]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [239]:
a.sum()

78

In [240]:
a.min()

1

In [241]:
a.max()

12

In [242]:
a.min(axis=0)

array([1, 2, 3, 4])

In [243]:
a.min(axis=1)

array([1, 5, 9])

In [244]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [245]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [246]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [249]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [250]:
np.random.random((3,2))

array([[0.17041808, 0.248334  ],
       [0.52955762, 0.43507641],
       [0.16022108, 0.59928408]])

In [251]:
# matrix arithmetic

In [253]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [255]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [256]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [257]:
ones_row = np.ones([1,2])
print(ones_row)

[[1. 1.]]


In [258]:
data + ones_row

array([[2., 3.],
       [4., 5.]])

In [260]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [261]:
print(a_1.shape)
print(a_2.shape)

(2, 3)
(3, 2)


In [262]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [264]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [265]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [270]:
data[0,1]

2

In [267]:
data[1,1]

4

In [274]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [275]:
data[0:2]

array([[1, 2],
       [3, 4]])

In [278]:
data[0:2, 1]

array([2, 4])

In [279]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [280]:
data.max()

6

In [281]:
data.min()

1

In [282]:
data.sum()

21

In [283]:
data.max(axis=1)

array([2, 4, 6])

In [284]:
data.max(axis=0)

array([5, 6])

In [285]:
# transposing and reshaping

In [286]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [287]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [288]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [289]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [290]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [291]:
arr = np.arange(6).reshape((2, 3))

In [292]:
print(arr)

[[0 1 2]
 [3 4 5]]


In [293]:
# ND Array

In [297]:
ndarr = np.array([[[1, 2], [3, 4]],
                 [[5, 6], [7, 8]]])

In [298]:
ndarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [299]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [300]:
np.zeros((4,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [301]:
np.random.random((4,3,2))

array([[[0.02577618, 0.66601651],
        [0.00088071, 0.70378908],
        [0.11737255, 0.36656515]],

       [[0.14392079, 0.07022179],
        [0.64735854, 0.08665788],
        [0.34550586, 0.13353544]],

       [[0.00145601, 0.2677914 ],
        [0.44254266, 0.49473802],
        [0.16150596, 0.52689719]],

       [[0.2506701 , 0.6609181 ],
        [0.80754922, 0.28049072],
        [0.06190462, 0.67964429]]])

In [302]:
# flatton

In [303]:
ndarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [304]:
ndarr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [305]:
a = np.random.random(5)

In [306]:
print(a)

[0.48032563 0.99066957 0.33017805 0.6051446  0.41084402]


In [307]:
a.shape # rank 1 Array

(5,)

In [308]:
a.T

array([0.48032563, 0.99066957, 0.33017805, 0.6051446 , 0.41084402])

In [309]:
np.dot(a, a.T)

1.8561492397626609

In [311]:
a = np.random.rand(5, 1) # column vector

In [312]:
print(a)

[[0.25146506]
 [0.55003679]
 [0.2118118 ]
 [0.05914173]
 [0.52589231]]


In [313]:
a.shape

(5, 1)

In [314]:
a.T

array([[0.25146506, 0.55003679, 0.2118118 , 0.05914173, 0.52589231]])

In [316]:
np.dot(a, a.T)

array([[0.06323468, 0.13831503, 0.05326327, 0.01487208, 0.13224354],
       [0.13831503, 0.30254047, 0.11650428, 0.03253013, 0.28926012],
       [0.05326327, 0.11650428, 0.04486424, 0.01252692, 0.1113902 ],
       [0.01487208, 0.03253013, 0.01252692, 0.00349774, 0.03110218],
       [0.13224354, 0.28926012, 0.1113902 , 0.03110218, 0.27656272]])

In [317]:
a = np.random.rand(1, 5)

In [318]:
a.shape

(1, 5)

In [319]:
a

array([[0.20317416, 0.56639182, 0.54354786, 0.88767193, 0.8762009 ]])

In [322]:
ndarr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [323]:
ndarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])