In [1]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd

In [2]:
x = [8.0, 1, 2.5, 4, 28.0]
x_with_nan = [8.0, 1, 2.5, math.nan, 4, 28.0]

In [3]:
x

[8.0, 1, 2.5, 4, 28.0]

In [4]:
x_with_nan

[8.0, 1, 2.5, nan, 4, 28.0]

In [5]:
y, y_with_nan = np.array(x), np.array(x_with_nan)
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)

In [6]:
y

array([ 8. ,  1. ,  2.5,  4. , 28. ])

In [7]:
y_with_nan

array([ 8. ,  1. ,  2.5,  nan,  4. , 28. ])

In [8]:
z

0     8.0
1     1.0
2     2.5
3     4.0
4    28.0
dtype: float64

In [9]:
z_with_nan

0     8.0
1     1.0
2     2.5
3     NaN
4     4.0
5    28.0
dtype: float64

In [10]:
# Mean

In [11]:
# Pure Python

mean_ = sum(x) / len(x)
mean_

8.7

In [13]:
# Satistics Lib

mean_ = statistics.mean(x)
mean_

8.7

In [14]:
# Statistics Lib with missing value

statistics.mean(x_with_nan)

nan

In [15]:
# Numpy 1

mean_ = np.mean(y)
mean_

8.7

In [16]:
# Numpy 2

mean_ = y.mean()
mean_

8.7

In [18]:
# Numpy with missing value

print(np.mean(y_with_nan))
print(y_with_nan.mean())

nan
nan


In [20]:
# Numpy ignore missing value

np.nanmean(y_with_nan)

8.7

In [22]:
# Pandas

mean = z.mean()
mean_

8.7

In [23]:
# Pandas with missing values

z_with_nan.mean()

8.7

In [24]:
# Median

In [25]:
# Statistics Lib

median_ = statistics.median(x)
median_

4

In [27]:
sorted(x)

[1, 2.5, 4, 8.0, 28.0]

In [29]:
sorted(x[:-1])

[1, 2.5, 4, 8.0]

In [31]:
statistics.median_low(x[:-1])

2.5

In [32]:
statistics.median_high(x[:-1])

4

In [33]:
statistics.median_low(x[:-1])

2.5

In [35]:
sorted(x_with_nan)

[1, 2.5, 4, 8.0, nan, 28.0]

In [36]:
# Statistics with missing values

statistics.median(x_with_nan)

6.0

In [37]:
# Numpy

median_ = np.median(y)
median_

4.0

In [38]:
np.median(y[:-1])

3.25

In [39]:
# Numpy with missing values

np.median(y_with_nan)

nan

In [41]:
np.nanmedian(y_with_nan)

4.0

In [42]:
# Pandas

z.median()

4.0

In [44]:
# Pandas with missing values

z_with_nan.median()

4.0

In [45]:
# Modus

In [46]:
u = [2, 3, 2, 8, 12]

v = [12, 15, 12, 15, 21,15, 12]

In [47]:
# Statistics Libs

mode_ = statistics.mode(u)
mode_

2

In [48]:
mode_ = statistics.mode(v)
mode_

StatisticsError: no unique mode; found 2 equally common values

In [49]:
u, v = np.array(u), np.array(v)

In [50]:
# Scipy

mode_ = scipy.stats.mode(u)
mode_

ModeResult(mode=array([2]), count=array([2]))

In [51]:
mode_ = scipy.stats.mode(v)
mode_

ModeResult(mode=array([12]), count=array([3]))

In [52]:
mode_.mode

array([12])

In [53]:
mode_.count

array([3])

In [54]:
u, v, w = pd.Series(u), pd.Series(v), pd.Series([2, 2, math.nan])

In [55]:
# Pandas

u.mode()

0    2
dtype: int32

In [57]:
v.mode()

0    12
1    15
dtype: int32

In [58]:
w.mode()

0    2.0
dtype: float64

In [59]:
# Statistics lib

var_ = statistics.variance(x)
var_

123.2

In [61]:
# Statistics lib with missing values

statistics.variance(x_with_nan)

nan

In [63]:
# Numpy 

var_ = np.var(y, ddof=1)
var_

123.19999999999999

In [64]:
var_ = y.var(ddof=1)
var_

123.19999999999999

In [65]:
# Numpy with missing values

np.var(y_with_nan, ddof=1)

nan

In [66]:
np.nanvar(y_with_nan, ddof=1)

123.19999999999999

In [67]:
# Pandas

z.var(ddof=1)

123.19999999999999

In [68]:
z_with_nan.var(ddof=1)

123.19999999999999

In [69]:
# Standard Deviation

In [70]:
# Statistics Lib

std_ = statistics.stdev(x)
std_

11.099549540409287

In [71]:
# Numpy

np.std(y, ddof=1)

11.099549540409285

In [72]:
y.std(ddof=1)

11.099549540409285

In [73]:
np.std(y_with_nan, ddof=1)

nan

In [74]:
# Pandas

z.std(ddof=1)

11.099549540409285

In [75]:
z_with_nan.std(ddof=1)

11.099549540409285

In [76]:
# Skewness

In [83]:
# Scipy

scipy.stats.skew(y, bias=False)

1.9470432273905927

In [84]:
scipy.stats.skew(y_with_nan)

nan

In [85]:
# Pandas

z.skew()

1.9470432273905924

In [86]:
z_with_nan.skew()

1.9470432273905924

In [87]:
# Percentile

In [88]:
# Numpy

np.percentile(y, 5) # 5%

1.3

In [89]:
np.percentile(y, 95) # 95&

23.999999999999996

In [90]:
np.percentile(y, [25,50,75])

array([2.5, 4. , 8. ])

In [91]:
np.median(y)

4.0

In [92]:
np.percentile(y_with_nan, 5)

nan

In [93]:
# Numpy with missing values

np.percentile(y_with_nan, 5)

nan

In [94]:
np.nanpercentile(y_with_nan, 5)

1.3

In [95]:
# Quantiles

In [96]:
# Numpy

np.quantile(y, 0.05)

1.3

In [97]:
np.quantile(y, 0.95)

23.999999999999996

In [98]:
np.nanquantile(y_with_nan, [0.25, 0.5, 0.75])

array([2.5, 4. , 8. ])

In [100]:
# Pandas

z.quantile(0.05)

1.3

In [101]:
z.quantile(0.95)

23.999999999999996

In [102]:
# Range

In [103]:
# Numpy

np.ptp(y)

27.0

In [104]:
y

array([ 8. ,  1. ,  2.5,  4. , 28. ])

In [105]:
np.ptp(z)

27.0

In [106]:
np.ptp(y_with_nan)

nan

In [107]:
np.ptp(z_with_nan)

nan

In [108]:
y.max() - y.min()

27.0

In [109]:
z.max() - z.min()

27.0

In [110]:
y_with_nan.max() - y_with_nan.min()

nan

In [113]:
# IQR

In [114]:
quartile_ = np.quantile(y, [0.25, 0.75])

In [115]:
quartile_

array([2.5, 8. ])

In [116]:
quartile_[1] - quartile_[0]

5.5

In [117]:
# Summary of Descriptive Stats

In [118]:
y

array([ 8. ,  1. ,  2.5,  4. , 28. ])

In [120]:
# Scipy

result = scipy.stats.describe(y, ddof=1, bias=False)

In [121]:
result

DescribeResult(nobs=5, minmax=(1.0, 28.0), mean=8.7, variance=123.19999999999999, skewness=1.9470432273905927, kurtosis=3.878019618875446)

In [123]:
result.nobs

5

In [124]:
result.minmax

(1.0, 28.0)

In [125]:
result.minmax[0]

1.0

In [126]:
result.minmax[1]

28.0

In [127]:
result.mean

8.7

In [128]:
result.variance

123.19999999999999

In [129]:
result.skewness

1.9470432273905927

In [130]:
result.kurtosis

3.878019618875446

In [131]:
# Pandas

result = z.describe()

In [132]:
result

count     5.00000
mean      8.70000
std      11.09955
min       1.00000
25%       2.50000
50%       4.00000
75%       8.00000
max      28.00000
dtype: float64

In [134]:
result['count']

5.0

In [135]:
result['mean']

8.7

In [136]:
result['std']

11.099549540409285

In [137]:
result['min']

1.0

In [138]:
result['max']

28.0

In [139]:
result['25%']

2.5

In [142]:
result['50%']

4.0

In [143]:
result['75%']

8.0